#!/bin//bash

echo "criando pastas"
mkdir /publico
mkdir /adm
mkdir /ven
mkdir /sec

echo "criando grupos"
groupadd grp_adm
groupadd grp_ven
groupadd grp_sec

echo "criando usuarios"
useradd user_adm1 -m -s /bin/bash -p $(openssl passwd -crypt senha) -G grp_adm
useradd user_adm2 -m -s /bin/bash -p $(openssl passwd -crypt senha) -G grp_adm
useradd user_adm3 -m -s /bin/bash -p $(openssl passwd -crypt senha) -G grp_adm

useradd user_ven1 -m -s /bin/bash -p $(openssl passwd -crypt senha) -G grp_ven
useradd user_ven2 -m -s /bin/bash -p $(openssl passwd -crypt senha) -G grp_ven
useradd user_ven3 -m -s /bin/bash -p $(openssl passwd -crypt senha) -G grp_ven

useradd user_sec1 -m -s /bin/bash -p $(openssl passwd -crypt senha) -G grp_sec
useradd user_sec2 -m -s /bin/bash -p $(openssl passwd -crypt senha) -G grp_sec
useradd user_sec3 -m -s /bin/bash -p $(openssl passwd -crypt senha) -G grp_sec

echo "setando grupos"
chown root:grp_adm /adm
chown root:grp_ven /ven
chown root:grp_sec /sec

echo "alterando permissoes de pasta"
chmod 770 /adm
chmod 770 /adm
chmod 770 /adm
chmod 777 /publico
